- name: Run Bridgecrew 
      id: Bridgecrew
      uses: bridgecrewio/bridgecrew-action@master
      with:
       api-key: ${{ secrets.BRIDGECREW_API_KEY }}
       directory: .
       framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
       output_format: cli
       quiet: true
       log_level: DEBUG # optional: set log level. Default WARNING

